config/routes.rb
Kanban::Application.routes.draw do
  match 'tasks/add_task'      => 'tasks#add_task',      :via => 'post'
  match 'tasks/change_status' => 'tasks#change_status', :via => 'post'
  resources :tasks

  root :to => "tasks#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :content,  :presence => true
  validates :status,   :presence => true
  #validates :priority, :presence => true
  #validates :owner,    :presence => true
end

# == Schema Information
#
# Table name: tasks
#
#  id         :integer         not null, primary key
#  content    :text
#  status     :string(255)
#  priority   :integer
#  owner      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
# -*- coding: utf-8 -*-
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @toDoTasks  = Task.find(:all, :conditions => ["status=?", "todo"],  :order => "priority desc, updated_at desc")
    @doingTasks = Task.find(:all, :conditions => ["status=?", "doing"], :order => "updated_at desc")
    @doneTasks  = Task.find(:all, :conditions => ["status=?", "done"],  :order => "updated_at desc")

    @form_action = 'add_task'
    @form_method = 'POST'
    @form_button = '追加する'
    @task = Task.new
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])

    @form_action = 'update'
    @form_method = 'PUT'
    @form_button = '編集する'

    #content属性に<br/>が含まれていた場合に"\n"に変換する(textarea表示用)
    @task.content = @task.content.gsub("<br/>", "\n")

    render :update do |page|
      #編集対象のタスクにvisual_effectをかける
      page.visual_effect :highlight, "#{@task.id}", :duration => 0.4
      #フォームを削除する
      page[:task_form].remove
      #フォームを挿入する
      page.insert_html :top, 'task_form_block', :partial => 'form'
      #編集対象のタスクにvisual_effectをかける
      page.visual_effect :highlight, "#{@task.id}", :duration => 0.6
    end
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    @task.update_attributes(params[:task])
    #改行が入力されていた場合に<br/>に変換する
    @task.content = @task.content.gsub("\n", "<br/>")
    @task.save

    render :update do |page|
      #_task.rhtml を書き換える
      page.replace "#{@task.id}", :partial => 'task', :object => @task
      #書き換えたタスクにvisual_effectをかける
      page.visual_effect :highlight, "#{@task.id}", :duration => 0.4
      #フォームを追加用に戻すため、いったん削除する
      page[:task_form].remove
      #フォームのアクションを'add_task'にする
      @form_action = 'add_task'
      #ボタン表示文字列を追加用にする
      @form_button = '追加する'
      @task.content = ""
      @task.owner = ""
      #フォームを挿入する
      page.insert_html :top, 'task_form_block', :partial => 'form'
    end

    #respond_to do |format|
      #if @task.update_attributes(params[:task])
        #format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        #format.xml  { head :ok }
      #else
        #format.html { render :action => "edit" }
        #format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      #end
    #end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end

  # ドラッグアンドドロップ時にタスクのステータスを変更する
  def change_status
    @task = Task.find(params[:id])
    if @task.update_attributes(:status => params[:status])
      render :update do |page|
        page.visual_effect :highlight, "#{params[:id]}", :duration => 0.6
      end
    end
  end

  # タスクを追加するメソッド
  def add_task
    @task = Task.new(params[:task])
    @task.status = 'todo'
    #改行が入力されていた場合に変換する
    @task.content = @task.content.gsub("\n", "")
    @task.save

    render :update do |page|
      #フォームをリセットする
      page.call 'Form.reset', 'task_form'
      #要素'todoCaption'の後ろにタスクを:partialで挿入する
      page.insert_html :top, 'todoCaption', :partial => 'task', :object => @task
      #タスクのdraggableを維持する
      page.draggable "#{@task.id}"
      #追加したタスクにvisual_effectをかける
      page.visual_effect :highlight,"#{@task.id}",:duration => 1
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanban</title>
  <%= stylesheet_link_tag "custom" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%#= error_messages_for 'task' %>
<div id='task_form_block'>
  <%= form_tag(url_for(:action => @form_action, :id => @task.id), :method => @form_method, :remote => true, :id => "task_form") do %>
    <%= text_area 'task', 'content', "rows" => 1, :class => "textbox" %>
    <!-- <label for="priority">あとで</label>
    <span><%#= radio_button("task", "priority", "1") %></span>
    <span><%#= radio_button("task", "priority", "2") %></span>
    <span><%#= radio_button("task", "priority", "3") %></span>
    <label for="priority">すぐに</label>
    <br />
    <label for="task_owner">誰が？</label>
    <%#= text_field 'task', 'owner', :class => "textbox" %>
    -->
    <%= submit_tag @form_button, :class => "button white medium" %>
  <% end -%>
</div>

app/views/tasks/_task.html.erb
<%
  case task.priority
  when 1
    @color = "#67BA37"
  when 2
    @color = "#9DB1FF"
  when 3
    @color = "#FF3333"
  else
    @color = "#9DB1FF"
  end
%>

<div id="<%= task.id %>" class="task" style="border:1px solid <%= @color %>">
  <%= task.content %>
  <span class="right">
    <%= link_to 'Edit', edit_task_path(task), :remote => true %>
    <%= link_to 'X', task, :confirm => 'このタスクを削除しますか？', :method => :delete %>
  </span>
  <%= draggable_element "#{task.id}", :revert => false %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div id="item_form_block" class="forms">
  <%= render :partial => 'form' %>
</div>

<table id="board" class="board">
  <tr>
    <td colspan="2" id="doing" class="doing">
      <table>
        <tr><td>
            迷い中
        </td></tr>
      </table>
      <div id="doingCaption" class="boardCaption">
        <%= render :partial => 'task', :collection => @doingTasks %>
      </div>
    </td>
    <%= drop_receiving_element 'doingCaption', :url => {:action => 'change_status', :status => 'doing'} %>
  </tr>

  <tr>
    <td id="todo" class="todo">
      <table>
        <tr><td>
            完全にやる
        </td></tr>
      </table>
      <div id="todoCaption" class="boardCaption">
        <%= render :partial => 'task', :collection => @toDoTasks %>
      </div>
    </td>
    <%= drop_receiving_element 'todoCaption', :url => {:action => 'change_status', :status => 'todo'} %>

    <td id="done" class="done">
      <table>
        <tr><td>
            完全にやらない
        </td></tr>
      </table>
      <div id="doneCaption" class="boardCaption">
        <%= render :partial => 'task', :collection => @doneTasks %>
      </div>
    </td>
    <%= drop_receiving_element 'doneCaption', :url => {:action => 'change_status', :status => 'done'} %>
  </tr>
</table>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>